# Generated by Django 2.2.13 on 2021-01-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='订单号', max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('order_status', models.CharField(choices=[('PENDING_PAYMENT', '等待支付'), ('COMPLETED_PAYMENT', '完成支付'), ('TRADE_CLOSED', '关闭订单'), ('TRADE_COMPLETED', '完成订单')], default='PENDING_PAYMENT', help_text='订单状态', max_length=20, verbose_name='订单状态')),
                ('order_amount', models.FloatField(default=0.0, help_text='订单金额', verbose_name='订单金额')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付时间', null=True, verbose_name='支付时间')),
                ('reci_address', models.CharField(default='', help_text='收货地址', max_length=200, verbose_name='收货地址')),
                ('reci_name', models.CharField(default='', help_text='收件人', max_length=20, verbose_name='收件人')),
                ('reci_mobile', models.CharField(help_text='联系电话', max_length=11, verbose_name='联系电话')),
                ('order_user', models.ForeignKey(help_text='下单用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-order_time'],
            },
        ),
    ]
