# Generated by Django 2.2.13 on 2021-01-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210124_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='pay_time',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='reci_address',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='reci_mobile',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='reci_name',
        ),
    ]
