# Generated by Django 2.2.13 on 2021-01-25 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210125_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'ordering': ['-created_time'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_time',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='下单时间'),
            preserve_default=False,
        ),
    ]
