# Generated by Django 2.2.13 on 2021-01-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210125_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='下单时间'),
        ),
    ]
